LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule expires_module modules/mod_expires.so

<VirtualHost *:80>
  ServerName pkp-ojs
  DocumentRoot /var/www/html
  RewriteEngine on
  AcceptPathInfo on

  <Directory /var/www/html>
    Options FollowSymLinks
    AllowOverride all
    Allow from all

    # This removes index.php from the url
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php/$1 [QSA,L]
  </Directory>

  SetEnvIf Request_URI "^/healthcheck.php$" dontlog
  ErrorLog  /dev/stderr
  CustomLog /dev/stdout combined env=!dontlog
</VirtualHost>
