name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.ojs_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        id: set_version
        run: |
          PKP_OJS_VERSION=$(sed -n 's/^PKP_OJS_VERSION="\([^"]*\)".*/\1/p' .config/workflows/ci-build-pkp-ojs.sh)
          echo "version=$PKP_OJS_VERSION" >> $GITHUB_OUTPUT

  build-pkp-ojs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pkp-ojs packages
        uses: actions/cache@v4
        with:
          key: pkp-ojs-${{ hashFiles('.config/workflows/ci-build-pkp-ojs.sh') }}
          path: |
            ~/.cache/pkp/ojs
          restore-keys: |
            pkp-ojs
      - name: Build pkp-ojs
        run: |
          echo "Versão recebida: ${{ needs.setup.outputs.version }}"
          bash .config/workflows/ci-build.sh
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run: |
          docker build --file src/pkp-ojs/Dockerfile     --pull --quiet --tag pkp/ojs:${{ needs.setup.outputs.version }} .
          docker build --file src/jobs/backup/Dockerfile --pull --quiet --tag pkp/ojs-job-backup:${{ needs.setup.outputs.version }} .
