name: CI
on:
  push:
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: teste
        run: |
          PKP_OJS_VERSION=$(sed -n 's/^PKP_OJS_VERSION="\([^"]*\)".*/\1/p' .config/workflows/ci-build-pkp-ojs.sh)
          echo "VERSION=$PKP_OJS_VERSION" >> $GITHUB_ENV

  build-pkp-ojs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Cache pkp-ojs packages
        uses: actions/cache@v4
        with:
          key: pkp-ojs-${{ hashFiles('.config/workflows/ci-build-pkp-ojs.sh') }}
          path: |
            ~/.cache/pkp/ojs
          restore-keys: |
            pkp-ojs
      - name: Build pkp-ojs
        run: |
          bash .config/workflows/ci-build.sh

  build-docker-images:
    needs: build-pkp-ojs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        run:
          docker build --file src/pkp-ojs/Dockerfile     --pull --quiet --tag pkp/ojs:${env.VERSION} .
          docker build --file src/jobs/backup/Dockerfile --pull --quiet --tag pkp/ojs-job-backup:${env.VERSION} .
